default: &default
  adapter: postgresql
  encoding: unicode
  username: jumper
  password: translations
  host: localhost

development:
  <<: *default
  database: translations_development

test:
  <<: *default
  database: translations_test
