toolbar:
  - undo redo | formatselect | fontselect | fontsizeselect | bold italic strikethrough hr blockquote | forecolor backcolor | removeformat
  - code codesample | image imagetools | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link uploadimage media table | fullscreen | preview |
plugins:
  - code print preview fullpage searchreplace autolink directionality visualblocks visualchars fullscreen link image imagetools media template codesample table charmap hr pagebreak nonbreaking anchor toc insertdatetime advlist lists wordcount textpattern help preview
fontsize_formats:
  '14px 16px 18px 20px 22px 24px 26px 28px 30px 32px 34px 36px 38px 40px 42px'
menubar:
  false
browser_spellcheck:
  true
